/**
 * Standard statuses representing the execution state of an Agent.
 */
export enum AgentStatus {
  WAITING = "WAITING",
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  SKIPPED = "SKIPPED"
}

/**
 * Shared context/state interface that flows through the agent pipeline.
 * Designed to be generic and extendable for any domain-specific keys.
 */
export interface AgentContext {
  /** Short-term or long-term parameters stored/retrieved by agents */
  memory: Record<string, unknown>;
  /** Pipeline run execution metadata, e.g., session tokens, system info */
  metadata: Record<string, unknown>;
  /** Dynamic context fields (e.g., studentProfile, recommendedCareer, etc.) */
  [key: string]: unknown;
}

/**
 * Structure representing the result returned by an Agent execution.
 */
export interface AgentResult {
  /** The execution outcome status */
  status: AgentStatus;
  /** Context updates containing key-value pairs to merge into the shared context */
  data?: Record<string, unknown>;
  /** Clear reasoning showing how the agent arrived at the conclusion/action */
  reasoning: string;
  /** Execution confidence score between 0.0 and 1.0 */
  confidence: number;
  /** Execution duration in milliseconds */
  executionTime: number;
  /** Suggested next agent ID to route to dynamically, overriding the sequence if set */
  nextAgent?: string;
  /** Error message details, populated if status is FAILED */
  error?: string;
}

/**
 * Base generic interface for all agents within the framework.
 */
export interface Agent<TContext extends AgentContext = AgentContext> {
  /** Unique identifier for the agent */
  readonly id: string;
  /** Readable name for the agent */
  readonly name: string;
  /** Brief description explaining the agent's function */
  readonly description: string;
  /** Version number of the agent (e.g., '1.0.0') */
  readonly version: string;
  /** Priority score used for ordering and resolution (higher runs first) */
  readonly priority: number;
  /** List of Agent IDs that must execute successfully before this agent can run */
  readonly dependencies: string[];

  /**
   * Executes the agent's logic on the shared context.
   * @param context The shared state context.
   * @returns A promise resolving to the AgentResult.
   */
  execute(context: TContext): Promise<AgentResult>;
}

/**
 * The execution plan generated by the PlannerAgent.
 */
export interface ExecutionPlan {
  /** The high-level user goal that prompted the plan creation */
  goal: string;
  /** Ordered list of Agent IDs determined to execute */
  steps: string[];
  /** Underlying reasoning explaining the planned sequence */
  reasoning: string;
}

/**
 * Single historical log entry representing a single agent execution step.
 */
export interface ExecutionLogEntry {
  agentId: string;
  agentName: string;
  startTime: number;
  endTime: number;
  executionDuration: number;
  status: AgentStatus;
  confidenceScore: number;
  reasoningSummary: string;
  error?: string;
}

/**
 * Final execution report returned by the AgentOrchestrator.
 */
export interface OrchestratorReport<TContext extends AgentContext = AgentContext> {
  /** True if the goal was successfully achieved without failing steps */
  success: boolean;
  /** The goal processed by the orchestrator (if planner-driven) */
  goal?: string;
  /** Snapshots of the context before starting */
  initialContext: TContext;
  /** Snapshots of the context after completed execution */
  finalContext: TContext;
  /** Chronological log entries for each step executed */
  logs: ExecutionLogEntry[];
  /** Total elapsed time of the entire orchestration process in milliseconds */
  totalExecutionTime: number;
  /** High level error message if the orchestration failed globally */
  error?: string;
}

/**
 * Enum listing all supported events in the framework lifecycle.
 */
export type FrameworkEventType = 
  | "AgentStarted" 
  | "AgentCompleted" 
  | "AgentFailed" 
  | "ContextUpdated";

/**
 * Maps event types to their corresponding payloads for strong type safety.
 */
export interface FrameworkEventDataMap {
  AgentStarted: { agentId: string; agentName: string; context: AgentContext };
  AgentCompleted: { agentId: string; agentName: string; result: AgentResult; context: AgentContext };
  AgentFailed: { agentId: string; agentName: string; error: string; context: AgentContext };
  ContextUpdated: { agentId: string; updatedKeys: string[]; context: AgentContext };
}

/**
 * Interface representing the Agent Registry.
 */
export interface AgentRegistry<TContext extends AgentContext = AgentContext> {
  /** Registers a new agent in the registry, validating duplicate registrations */
  register(agent: Agent<TContext>): void;
  /** Resolves an agent by its unique identifier */
  get(id: string): Agent<TContext> | undefined;
  /** Retrieves all registered agents */
  getAll(): Agent<TContext>[];
  /** Checks if an agent with the given ID exists */
  has(id: string): boolean;
}
