import { Agent, AgentContext, AgentResult, AgentStatus } from "../types/agent";
import { Logger } from "../services/logger";
import { ConsoleLogger } from "../services/logger";

/**
 * Abstract base class providing common middleware functionalities (logging, timing, hooks, error handling)
 * that all agents in the framework extend.
 */
export abstract class BaseAgent<TContext extends AgentContext = AgentContext>
  implements Agent<TContext>
{
  public abstract readonly id: string;
  public abstract readonly name: string;
  public abstract readonly description: string;
  public abstract readonly version: string;
  public abstract readonly priority: number;
  public abstract readonly dependencies: string[];

  protected readonly logger: Logger;

  /**
   * Initializes the BaseAgent.
   * @param logger Optional Logger service instance. If omitted, ConsoleLogger is instantiated.
   */
  constructor(logger?: Logger) {
    // Provide fallback to default ConsoleLogger configured with subclass constructor name
    this.logger = logger || new ConsoleLogger(this.constructor.name);
  }

  /**
   * Pre-execution validation hook.
   * Override this to inspect context before running.
   * @param context Shared pipeline context.
   * @returns True if the agent should execute, False if it should be skipped.
   */
  protected validate(context: TContext): boolean | Promise<boolean> {
    void context; // Satisfy strict noUnusedParameters
    return true;
  }

  /**
   * Lifecycle hook executed after validation succeeds and before the main run() logic.
   * @param context Shared pipeline context.
   */
  protected preExecute(context: TContext): void | Promise<void> {
    void context; // Satisfy strict noUnusedParameters
  }

  /**
   * Lifecycle hook executed after run() finishes, regardless of success, skipped, or failed status.
   * Useful for teardown, event triggers, or telemetry reporting.
   * @param context Shared pipeline context.
   * @param result Final result generated by the execution process.
   */
  protected postExecute(
    context: TContext,
    result: AgentResult
  ): void | Promise<void> {
    void context; // Satisfy strict noUnusedParameters
    void result; // Satisfy strict noUnusedParameters
  }

  /**
   * Core agent processing method to be implemented by subclass.
   * Focuses strictly on business/intelligence reasoning, isolated from boilerplate timing & try-catch logic.
   * @param context Shared pipeline context.
   */
  protected abstract run(
    context: TContext
  ): Promise<
    Pick<
      AgentResult,
      "status" | "data" | "reasoning" | "confidence" | "nextAgent"
    >
  >;

  /**
   * Standardized implementation of execute wrapper to run lifecycle hooks, validate, measure execution time,
   * write standard logs, and catch raw exceptions.
   * @param context Shared pipeline context.
   */
  public async execute(context: TContext): Promise<AgentResult> {
    const startTime = performance.now();
    this.logger.info(`Executing agent: ${this.name} (${this.id})`);

    let result: AgentResult;

    try {
      // 1. Run validation check
      const isValid = await this.validate(context);
      if (!isValid) {
        const endTime = performance.now();
        const duration = endTime - startTime;
        this.logger.warn(`Validation check failed. Skipping agent execution.`);
        
        result = {
          status: AgentStatus.SKIPPED,
          reasoning: "Context validation hook returned false.",
          confidence: 0.0,
          executionTime: duration,
        };

        await this.postExecute(context, result);
        return result;
      }

      // 2. Run preExecute hook
      await this.preExecute(context);

      // 3. Run the primary logic
      const runResult = await this.run(context);

      const endTime = performance.now();
      const duration = endTime - startTime;

      result = {
        ...runResult,
        executionTime: duration,
      };

      this.logger.info(
        `Agent execution finished with status '${result.status}' (Duration: ${duration.toFixed(2)}ms, Confidence: ${result.confidence})`
      );

      // 4. Run postExecute hook
      await this.postExecute(context, result);
      return result;

    } catch (error) {
      const endTime = performance.now();
      const duration = endTime - startTime;
      const errMsg = error instanceof Error ? error.message : String(error);

      this.logger.error(`Unhandled agent error: ${errMsg}`, {
        stack: error instanceof Error ? error.stack : undefined,
      });

      result = {
        status: AgentStatus.FAILED,
        reasoning: `Unhandled execution exception: ${errMsg}`,
        confidence: 0.0,
        executionTime: duration,
        error: errMsg,
      };

      // Attempt to execute post-execute hook even on fatal errors
      try {
        await this.postExecute(context, result);
      } catch (hookError) {
        this.logger.error(
          `Error occurred in postExecute hook during error state handling: ${hookError instanceof Error ? hookError.message : String(hookError)}`
        );
      }

      return result;
    }
  }
}
